name: AntiElytraTarget
version: '1.0.0'
main: com.worty1.antiElytraTarget.AntiElytraTarget
api-version: '1.21'
author: Worty1
website: https://github.com/WortyXD/AntiElytraTarget

commands:
  antielytratarget:
    aliases: [aet, antielytra]
    permission: aet.use
    usage: /aet <args>

permissions:
  aet.use:
    default: true

  aet.alert:
    default: op

  aet.admin:
    default: op

  aet.bypass:
    default: false
